# build environment
FROM node:8-alpine as react-build
WORKDIR /app
COPY . ./
RUN yarn
RUN yarn build

# server environment
FROM nginx:alpine
COPY ./nginx/nginx.conf /etc/nginx/conf.d/configfile.template
COPY ./keys/hackathon.crt /etc/nginx/hackathon.crt
COPY ./keys/hackathon.key /etc/nginx/hackathon.key
ENV PORT 8080
ENV HOST 0.0.0.0
RUN sh -c "envsubst '\$PORT'  < /etc/nginx/conf.d/configfile.template > /etc/nginx/conf.d/default.conf"
COPY --from=react-build /app/build /usr/share/nginx/html
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]